/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Main.content;
 

import javax.swing.JOptionPane;
import java.text.DecimalFormat;
import Pizzaa.components.Deluxe_Pizza;
import Pizzaa.components.Special_Pizza;
import Pizzaa.components.Promo_Pizza;
import java.util.Date;
import java.text.SimpleDateFormat;

/**
 *
 * @author john clarence
 */
public class Pizza_Class_Convertion extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    public Pizza_Class_Convertion() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Dpizza = new javax.swing.JRadioButton();
        Spizza = new javax.swing.JRadioButton();
        Ppizza = new javax.swing.JRadioButton();
        jPanel1 = new javax.swing.JPanel();
        chili = new javax.swing.JCheckBox();
        ham = new javax.swing.JCheckBox();
        bacon = new javax.swing.JCheckBox();
        cheese = new javax.swing.JCheckBox();
        Pepper = new javax.swing.JCheckBox();
        onions = new javax.swing.JCheckBox();
        jLabel4 = new javax.swing.JLabel();
        mushroom = new javax.swing.JCheckBox();
        text1 = new javax.swing.JTextField();
        text2 = new javax.swing.JTextField();
        LogOut = new javax.swing.JButton();
        receipt = new javax.swing.JButton();
        calculation = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        clear = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Dpizza.setFont(new java.awt.Font("Segoe UI Variable", 1, 18)); // NOI18N
        Dpizza.setForeground(new java.awt.Color(154, 59, 59));
        Dpizza.setText("Deluxe Pizza");
        Dpizza.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DpizzaActionPerformed(evt);
            }
        });
        getContentPane().add(Dpizza, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 160, 150, -1));

        Spizza.setFont(new java.awt.Font("Segoe UI Variable", 1, 18)); // NOI18N
        Spizza.setForeground(new java.awt.Color(154, 59, 59));
        Spizza.setText("Special Pizza");
        Spizza.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SpizzaActionPerformed(evt);
            }
        });
        getContentPane().add(Spizza, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 160, 140, -1));

        Ppizza.setFont(new java.awt.Font("Segoe UI Variable", 1, 18)); // NOI18N
        Ppizza.setForeground(new java.awt.Color(154, 59, 59));
        Ppizza.setText("Promo Pizza");
        Ppizza.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PpizzaActionPerformed(evt);
            }
        });
        getContentPane().add(Ppizza, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 160, 140, -1));

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel1.setDoubleBuffered(false);

        chili.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        chili.setForeground(new java.awt.Color(67, 83, 52));
        chili.setText("Chili");

        ham.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        ham.setForeground(new java.awt.Color(67, 83, 52));
        ham.setText("Ham");

        bacon.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        bacon.setForeground(new java.awt.Color(67, 83, 52));
        bacon.setText("Bacon");

        cheese.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        cheese.setForeground(new java.awt.Color(67, 83, 52));
        cheese.setText("Cheese");

        Pepper.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Pepper.setForeground(new java.awt.Color(67, 83, 52));
        Pepper.setText("Pepper");
        Pepper.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PepperActionPerformed(evt);
            }
        });

        onions.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        onions.setForeground(new java.awt.Color(67, 83, 52));
        onions.setText("Onions");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(158, 179, 132));
        jLabel4.setText("Ingredients");

        mushroom.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        mushroom.setForeground(new java.awt.Color(67, 83, 52));
        mushroom.setText("Mushroom");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(135, 135, 135)
                .addComponent(jLabel4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(cheese, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bacon, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(mushroom, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(ham, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(chili, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(Pepper, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(onions, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(22, 22, 22))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chili)
                    .addComponent(ham)
                    .addComponent(bacon))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cheese)
                    .addComponent(Pepper)
                    .addComponent(onions))
                .addGap(18, 18, 18)
                .addComponent(mushroom)
                .addGap(16, 16, 16))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 240, -1, -1));
        getContentPane().add(text1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 470, 206, 44));
        getContentPane().add(text2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 520, 206, 46));

        LogOut.setBackground(new java.awt.Color(167, 39, 49));
        LogOut.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        LogOut.setForeground(new java.awt.Color(12, 9, 13));
        LogOut.setText("Log out");
        LogOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogOutActionPerformed(evt);
            }
        });
        getContentPane().add(LogOut, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 530, 79, 70));

        receipt.setBackground(new java.awt.Color(71, 121, 152));
        receipt.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        receipt.setForeground(new java.awt.Color(12, 9, 13));
        receipt.setText("Receipt");
        receipt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                receiptActionPerformed(evt);
            }
        });
        getContentPane().add(receipt, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 450, 79, 70));

        calculation.setBackground(new java.awt.Color(196, 214, 176));
        calculation.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        calculation.setForeground(new java.awt.Color(12, 9, 13));
        calculation.setText("Calculate");
        calculation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calculationActionPerformed(evt);
            }
        });
        getContentPane().add(calculation, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 450, -1, 70));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(192, 130, 97));
        jLabel1.setText("PRICE: 185");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 200, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(192, 130, 97));
        jLabel2.setText("PRICE: 250");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 200, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(192, 130, 97));
        jLabel3.setText("PRICE: 290");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 200, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        jLabel5.setText("EMPLOYEE / USER (admin) / DASHBOARD");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, -1, -1));

        clear.setBackground(new java.awt.Color(246, 71, 64));
        clear.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        clear.setForeground(new java.awt.Color(12, 9, 13));
        clear.setText("Clear");
        clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearActionPerformed(evt);
            }
        });
        getContentPane().add(clear, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 530, 79, 70));

        jLabel6.setFont(new java.awt.Font("Yu Gothic UI", 1, 36)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(210, 19, 18));
        jLabel6.setText("RENCE PIZZA SHOP");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 60, -1, 29));

        jLabel7.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(216, 63, 49));
        jLabel7.setText("Menu");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 110, -1, -1));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 640, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 0, 40, 640));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel8.setText("Amount of Order :");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 480, -1, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel9.setText("Total: ");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 530, 50, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void LogOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogOutActionPerformed
        // TODO add your handling code here:
        System.out.println("\n");
        System.out.println("User Succesfully Disonnected! ");   //Display A message in the output 
         Date currentDate = new Date();

        // Create a SimpleDateFormat object to format the date and time
        SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");

        // Format the date and time as a string
        String formattedDate = dateFormat.format(currentDate);

        // Print the formatted date and time to the console
        System.out.println(" Date and time: " + formattedDate);
        System.exit(0);
        
        System.out.println("\n");
        
        
    }//GEN-LAST:event_LogOutActionPerformed

    private void DpizzaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DpizzaActionPerformed
        // TODO add your handling code here:
        if(Dpizza.isSelected()){
            Spizza.setSelected(false);
            Ppizza.setSelected(false);
            
            //Ingredients
            bacon.setSelected(true);
            cheese.setSelected(true);
            ham.setSelected(true);
            chili.setSelected(true);
            onions.setSelected(true);
        }
    }//GEN-LAST:event_DpizzaActionPerformed

    private void clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearActionPerformed
        // TODO add your handling code here:
            text1.setText("");
            text2.setText("");
            Ppizza.setSelected(false);
            Dpizza.setSelected(false);
            Spizza.setSelected(false);
            
            //Ingredients
             Ppizza.setSelected(false);
             bacon.setSelected(false);
             cheese.setSelected(false);
             ham.setSelected(false);
             chili.setSelected(false);
             onions.setSelected(false);
             Pepper.setSelected(false);
             mushroom.setSelected(false);
        
    }//GEN-LAST:event_clearActionPerformed

    private void SpizzaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SpizzaActionPerformed
        // TODO add your handling code here:
        if(Spizza.isSelected()){
            Dpizza.setSelected(false);
            Ppizza.setSelected(false);
            
            //Ingredients
            bacon.setSelected(true);
            cheese.setSelected(true);
            ham.setSelected(true);
            chili.setSelected(true);
            onions.setSelected(true);
            Pepper.setSelected(true);
            mushroom.setSelected(true);
        }
    }//GEN-LAST:event_SpizzaActionPerformed

    private void PepperActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PepperActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PepperActionPerformed

    private void PpizzaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PpizzaActionPerformed
        // TODO add your handling code here:
        if(Ppizza.isSelected()){
            Spizza.setSelected(false);
            Dpizza.setSelected(false);
            
            //Ingredients
            bacon.setSelected(true);
            cheese.setSelected(true);
            ham.setSelected(true);
            chili.setSelected(true);
            onions.setSelected(true);
            Pepper.setSelected(true);
            mushroom.setSelected(true);
        }
    }//GEN-LAST:event_PpizzaActionPerformed

    private void calculationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calculationActionPerformed
        // TODO add your handling code here:
//         int a;
//         int option; 
//         int optionTextField;
//         int total = 0;
//         
//         DecimalFormat decimalFormat = new DecimalFormat("#,###"); 
//          
//         optionTextField = Integer.parseInt(text1.getText());
//        
//          if(Dpizza.isSelected()){
//              option = optionTextField * 185;
//             total += option;
//             text2.setText("P " + total);
//          }

            try {
                if (Dpizza.isSelected()) {
                    Deluxe_Pizza pizzaOrder = new Deluxe_Pizza();
                    int optionTextField = Integer.parseInt(text1.getText());
                    pizzaOrder.processPizzaOrder(optionTextField);
                    pizzaOrder.getTotal();
                    text2.setText(pizzaOrder.getFormattedTotal());

                } else if (Spizza.isSelected()) {
                    Special_Pizza pizzaOrder = new Special_Pizza();
                    int optionTextField = Integer.parseInt(text1.getText());
                    pizzaOrder.processThis(optionTextField);
                    int total = pizzaOrder.getTotal();
                    text2.setText(pizzaOrder.Formatted());

                } else if (Ppizza.isSelected()) {
                    Promo_Pizza pizzaOrder = new Promo_Pizza();
                    int optionTextField = Integer.parseInt(text1.getText());
                    pizzaOrder.processPizzaOrder(optionTextField);
                    int total = pizzaOrder.getTotal();
                    text2.setText(pizzaOrder.getFormattedTotal());

                }
                System.out.println("Invalid input-- null");
                
            } catch (NumberFormatException e) {
                text2.setText("Invalid input!");
                System.out.println("Invalid input-- No order amount");
            }
    }//GEN-LAST:event_calculationActionPerformed

    private void receiptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_receiptActionPerformed
        // TODO add your handling code here: 
       
          try {
                if (Dpizza.isSelected()) {

             Deluxe_Pizza pizzaOrder = new Deluxe_Pizza();

             int optionTextField = Integer.parseInt(text1.getText()); 

             pizzaOrder.processPizzaOrder(optionTextField);

             int total = pizzaOrder.getTotal();
             text2.setText("" + pizzaOrder.getFormattedTotal());


             DecimalFormat decimalFormat = new DecimalFormat("#,###");
             String title = "Customer Receipt";
             String message = "Customer total: " + "₱ " + decimalFormat.format(total) + "\n" + "Ordered Pizza: " + optionTextField;

             JOptionPane.showMessageDialog(rootPane, message, title, JOptionPane.INFORMATION_MESSAGE);    

                    text1.setText("");
                    text2.setText("");
                    Dpizza.setSelected(false);
                    Spizza.setSelected(false);
                    Ppizza.setSelected(false);
                    bacon.setSelected(false);
                    cheese.setSelected(false);
                    ham.setSelected(false);
                    chili.setSelected(false);
                    onions.setSelected(false);

        }   else if(Spizza.isSelected()){

                 Special_Pizza pizzaOrder = new Special_Pizza();

                int optionTextField = Integer.parseInt(text1.getText()); 

                 pizzaOrder.processThis(optionTextField);

                int total = pizzaOrder.getTotal();
                text2.setText("" + pizzaOrder.Formatted());


                 DecimalFormat decimalFormat = new DecimalFormat("#,###");
                 String title = "Customer Receipt";
                 String message = "Customer total: "+ "₱ " + decimalFormat.format(total) + "\n" + "Ordered Pizza: " + optionTextField;

                JOptionPane.showMessageDialog(rootPane, message, title, JOptionPane.INFORMATION_MESSAGE);    

                    text1.setText("");
                    text2.setText("");
                    Dpizza.setSelected(false);
                    Spizza.setSelected(false);
                    Ppizza.setSelected(false);
                    bacon.setSelected(false);
                    cheese.setSelected(false);
                    ham.setSelected(false);
                    chili.setSelected(false);
                    onions.setSelected(false);
                    Pepper.setSelected(false);
                    mushroom.setSelected(false);

              }else if(Ppizza.isSelected()){

                  Promo_Pizza pizzaOrder = new Promo_Pizza();

                        int optionTextField = Integer.parseInt(text1.getText()); 

                        pizzaOrder.processPizzaOrder(optionTextField);

                        int total = pizzaOrder.getTotal();
                        text2.setText("" + pizzaOrder.getFormattedTotal());


                        DecimalFormat decimalFormat = new DecimalFormat("#,###");
                        String title = "Customer Receipt";
                        String message = "Customer total: " + "₱ " + decimalFormat.format(total) + "\n" + "Ordered Pizza: " + optionTextField;

                        JOptionPane.showMessageDialog(rootPane, message, title, JOptionPane.INFORMATION_MESSAGE);    

                        text1.setText("");
                        text2.setText("");
                        Dpizza.setSelected(false);
                        Spizza.setSelected(false);
                        Ppizza.setSelected(false);
                        bacon.setSelected(false);
                        cheese.setSelected(false);
                        ham.setSelected(false);
                        chili.setSelected(false);
                        onions.setSelected(false);
                        Pepper.setSelected(false);
                        mushroom.setSelected(false);  
              }


                    System.out.println("Invalid input-- no input ");
                }catch(NumberFormatException e){
                          text2.setText("Invalid input! ");
                System.out.println("Invalid input--- No Order Amount ");
        }
       
               
    
    }//GEN-LAST:event_receiptActionPerformed
 
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pizza_Class_Convertion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pizza_Class_Convertion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pizza_Class_Convertion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pizza_Class_Convertion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Pizza_Class_Convertion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton Dpizza;
    private javax.swing.JButton LogOut;
    private javax.swing.JCheckBox Pepper;
    private javax.swing.JRadioButton Ppizza;
    private javax.swing.JRadioButton Spizza;
    private javax.swing.JCheckBox bacon;
    private javax.swing.JButton calculation;
    private javax.swing.JCheckBox cheese;
    private javax.swing.JCheckBox chili;
    private javax.swing.JButton clear;
    private javax.swing.JCheckBox ham;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JCheckBox mushroom;
    private javax.swing.JCheckBox onions;
    private javax.swing.JButton receipt;
    private javax.swing.JTextField text1;
    private javax.swing.JTextField text2;
    // End of variables declaration//GEN-END:variables

    private int calculate() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
}
